build: false

environment:
  matrix:
    - PYTHON: C:\Python27
      PYTHON_VERSION: 2.7
      PYTHON_ARCH: 32

    - PYTHON: C:\Python34
      PYTHON_VERSION: 3.4
      PYTHON_ARCH: 32

    - PYTHON: C:\Python35
      PYTHON_VERSION: 3.5
      PYTHON_ARCH: 32

    - PYTHON: C:\Python36
      PYTHON_VERSION: 3.6
      PYTHON_ARCH: 32

cache:
  # Cache downloaded pip packages and built wheels.
  - '%LOCALAPPDATA%\pip\Cache\http'
  - '%LOCALAPPDATA%\pip\Cache\wheels'

init:
  - ECHO %PYTHON% %PYTHON_VERSION% %PYTHON_ARCH%

# Command(s) to install dependencies
install:
  - set PATH=%PYTHON%;%PYTHON%\\Scripts;%PATH% # Prepend newly installed Python to the PATH of this build
  - python --version # Verify version
  - python -m pip install --upgrade pip # Gives access denied error when not using 'python -m' prefix
  - pip install --upgrade six # Upgrade six because Python 3.4 is packaged with 1.10.0 and we need at least 1.11.0
  - pip install -e .[dev,test]

# Build command(s)
test_script:
  - python setup.py test