# Version format
version: '{build}'

# Build and deploy is not needed for Python
build: off
deploy: off

# Do not build feature branch with open Pull Requests
skip_branch_with_pr: true

# Do not build on tags (GitHub and BitBucket)
skip_tags: true

# Build environment
environment:
  matrix:
    - PYTHON: C:\Python27-x64
      PYTHON_VERSION: 2.7
      PYTHON_ARCH: 64

    - PYTHON: C:\Python34-x64
      PYTHON_VERSION: 3.4
      PYTHON_ARCH: 64

    - PYTHON: C:\Python35-x64
      PYTHON_VERSION: 3.5
      PYTHON_ARCH: 64

    - PYTHON: C:\Python36-x64
      PYTHON_VERSION: 3.6
      PYTHON_ARCH: 64

# Build matrix
matrix:
  fast_finish: true # Finish build immediately once one of the jobs fails.

# Caching
cache:
  - '%LOCALAPPDATA%\pip\Cache'
  - '%APPDATA%\npm-cache'
  - 'node_modules'

# Command(s) to execute before starting
init:
  - ECHO %PYTHON% %PYTHON_VERSION% %PYTHON_ARCH%
  # If there is a newer build queued for the same PR, cancel this one.
  # The AppVeyor 'rollout builds' option is supposed to serve the same
  # purpose but it is problematic because it tends to cancel builds pushed
  # directly to master instead of just PR builds (or the converse).
  # credits: JuliaLang developers.
  - ps: if ($env:APPVEYOR_PULL_REQUEST_NUMBER -and $env:APPVEYOR_BUILD_NUMBER -ne ((Invoke-RestMethod `
        https://ci.appveyor.com/api/projects/$env:APPVEYOR_ACCOUNT_NAME/$env:APPVEYOR_PROJECT_SLUG/history?recordsNumber=50).builds | `
        Where-Object pullRequestId -eq $env:APPVEYOR_PULL_REQUEST_NUMBER)[0].buildNumber) { `
          throw "There are newer queued builds for this pull request, failing early." }

# Command(s) to install dependencies
install:
  - set PATH=%PYTHON%;%PYTHON%\\Scripts;%PATH% # Prepend newly installed Python to the PATH of this build
  - python --version # Verify version
  - python -c "import struct; print(struct.calcsize('P') * 8)" # Verify architecture
  - python -m pip install --upgrade pip # Gives access denied error when not using 'python -m' prefix
  - pip install --upgrade six # Upgrade six because Python 3.4 is packaged with 1.10.0 and we need at least 1.11.0
  - pip install -e .[dev,test]
  - pip install coverage
  - npm install

# Build command(s)
before_test:
  - npm run lint

test_script:
  - coverage run --branch --source=autosubliminal setup.py test
  - coverage report