language: python

# Build matrix
matrix:
  include:
    - python: 2.7
    - python: 3.5
    - python: 3.6
    - python: 3.7
      dist: xenial # Required for Python >= 3.7
      sudo: true # Required for Python >= 3.7
  fast_finish: true # Finish build immediately once one of the jobs fails.

# Caching
before_cache:
  - rm -f $HOME/.cache/pip/log/debug.log

cache:
  npm: true
  directories:
    - $HOME/.cache/pip
    - node_modules

# Install command(s)
before_install:
  - export BOTO_CONFIG=/dev/null # FIXME: Workaround for https://github.com/travis-ci/travis-ci/issues/7940

install:
  - pip install --upgrade pip
  - pip install --upgrade six # Upgrade six because Python 3.4 is packaged with 1.10.0 and we need at least 1.11.0
  - pip install -e .[dev,test]
  - pip install coveralls
  - npm install

# Build command(s)
before_script:
  - npm run eslint
  - npm run stylelint

script:
  - coverage run setup.py test # Coverage configuration is done in .coveragerc
  - coverage report

# After success command(s)
after_success:
  - coveralls
