# Language
language: python

# OS
os: linux

# OS distribution
dist: xenial

# Build matrix (jobs)
jobs:
  include:
    - python: 3.6
    - python: 3.7
    - python: 3.8
  fast_finish: true # Finish build immediately once one of the jobs fails.

# Caching
before_cache:
  - rm -f $HOME/.cache/pip/log/debug.log

cache:
  npm: true
  directories:
    - $HOME/.cache/pip
    - web/autosubliminal/node_modules

# Install command(s)
before_install:
  - export BOTO_CONFIG=/dev/null # FIXME: Workaround for https://github.com/travis-ci/travis-ci/issues/7940

install:
  # Backend code
  # Install/upgrade python dependencies
  - pip install --upgrade pip
  - pip install --upgrade six # Upgrade six to latest version to prevent build errors
  - pip install --upgrade pytest # Upgrade pytest to latest version to prevent build errors
  - pip install -e .[dev,test]
  - pip install coveralls

  # Frontend code
  - cd web/autosubliminal
  # Install minimal required node version from package.json
  - nvm install "$(jq -r '.engines.node' package.json | sed 's/[>=]//g')"
  - node --version
  - npm --version
  # Install npm dependencies
  - npm install
  - cd ../..

# Build & Test command(s)
before_script:
  - flake8 -v # Python linting, configuration is done in .flake8
  - cd web/autosubliminal # Angular linting
  - npm run lint
  - cd ../..

script:
  - coverage run setup.py test # Coverage configuration is done in .coveragerc
  - coverage report

# After success command(s)
after_success:
  - coveralls
