sudo: false

language: python

# Python versions to build
python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"

# Build matrix
matrix:
  fast_finish: true # Finish build immediately once one of the jobs fails.

# Caching
cache:
  directories:
    - $HOME/.cache/pip

before_cache:
  - rm -f $HOME/.cache/pip/log/debug.log

# Command(s) to install dependencies
install:
  - pip install --upgrade pip
  - pip install --upgrade six # Upgrade six because Python 3.4 is packaged with 1.10.0 and we need at least 1.11.0
  - pip install -e .[dev,test]
  - pip install coveralls

# Build command(s)
script:
  - coverage run setup.py test # Coverage configuration is done in .coveragerc
  - coverage report

# After success command(s)
after_success:
  - coveralls
