# Language
language: python

# OS
os: linux

# OS distribution
dist: xenial

# Build matrix (jobs)
jobs:
  include:
    - python: 2.7
    - python: 3.5
    - python: 3.6
    - python: 3.7
  fast_finish: true # Finish build immediately once one of the jobs fails.

# Caching
before_cache:
  - rm -f $HOME/.cache/pip/log/debug.log

cache:
  npm: true
  directories:
    - $HOME/.cache/pip
    - node_modules

# Install command(s)
before_install:
  - export BOTO_CONFIG=/dev/null # FIXME: Workaround for https://github.com/travis-ci/travis-ci/issues/7940

install:
  - pip install --upgrade pip
  - pip install --upgrade six # Upgrade pytest to latest version to prevent build errors
  - pip install --upgrade pytest # Upgrade pytest to latest version to prevent build errors
  - pip install -e .[dev,test]
  - pip install coveralls
  - node --version
  - npm --version
  - npm install

# Build command(s)
before_script:
  - npm run eslint
  - npm run stylelint

script:
  - coverage run setup.py test # Coverage configuration is done in .coveragerc
  - coverage report

# After success command(s)
after_success:
  - coveralls
