#!/usr/bin/env python




##################################################
## DEPENDENCIES
import sys
import os
import os.path
try:
    import builtins as builtin
except ImportError:
    import __builtin__ as builtin
from os.path import getmtime, exists
import time
import types
from Cheetah.Version import MinCompatibleVersion as RequiredCheetahVersion
from Cheetah.Version import MinCompatibleVersionTuple as RequiredCheetahVersionTuple
from Cheetah.Template import Template
from Cheetah.DummyTransaction import *
from Cheetah.NameMapper import NotFound, valueForName, valueFromSearchList, valueFromFrameOrSearchList
from Cheetah.CacheRegion import CacheRegion
import Cheetah.Filters as Filters
import Cheetah.ErrorCatchers as ErrorCatchers
import autosubliminal

##################################################
## MODULE CONSTANTS
VFFSL=valueFromFrameOrSearchList
VFSL=valueFromSearchList
VFN=valueForName
currentTime=time.time
__CHEETAH_version__ = '2.4.4'
__CHEETAH_versionTuple__ = (2, 4, 4, 'development', 0)
__CHEETAH_genTime__ = 1512421115.662
__CHEETAH_genTimestamp__ = 'Mon Dec 04 21:58:35 2017'
__CHEETAH_src__ = 'PageTemplate.tmpl'
__CHEETAH_srcLastModified__ = 'Mon Dec 04 21:54:02 2017'
__CHEETAH_docstring__ = 'Autogenerated by Cheetah: The Python-Powered Template Engine'

if __CHEETAH_versionTuple__ < RequiredCheetahVersionTuple:
    raise AssertionError(
      'This template was compiled with Cheetah version'
      ' %s. Templates compiled before version %s must be recompiled.'%(
         __CHEETAH_version__, RequiredCheetahVersion))

##################################################
## CLASSES

class PageTemplate(Template):

    ##################################################
    ## CHEETAH GENERATED METHODS


    def __init__(self, *args, **KWs):

        super(PageTemplate, self).__init__(*args, **KWs)
        if not self._CHEETAH__instanceInitialized:
            cheetahKWArgs = {}
            allowedKWs = 'searchList namespaces filter filtersLib errorCatcher'.split()
            for k,v in KWs.items():
                if k in allowedKWs: cheetahKWArgs[k] = v
            self._initCheetahInstance(**cheetahKWArgs)
        

    def headerContent(self, **KWS):



        ## CHEETAH: generated from #block headerContent at line 11, col 5.
        trans = KWS.get("trans")
        if (not trans and not self._CHEETAH__isBuffering and not callable(self.transaction)):
            trans = self.transaction # is None unless self.awake() was called
        if not trans:
            trans = DummyTransaction()
            _dummyTrans = True
        else: _dummyTrans = False
        write = trans.response().write
        SL = self._CHEETAH__searchList
        _filter = self._CHEETAH__currentFilter
        
        ########################################
        ## START - generated method body
        
        write(u'''    <!-- PLACEHOLER HEADERCONTENT -->
''')
        
        ########################################
        ## END - generated method body
        
        return _dummyTrans and trans.response().getvalue() or ""
        

    def bodyContent(self, **KWS):



        ## CHEETAH: generated from #block bodyContent at line 27, col 9.
        trans = KWS.get("trans")
        if (not trans and not self._CHEETAH__isBuffering and not callable(self.transaction)):
            trans = self.transaction # is None unless self.awake() was called
        if not trans:
            trans = DummyTransaction()
            _dummyTrans = True
        else: _dummyTrans = False
        write = trans.response().write
        SL = self._CHEETAH__searchList
        _filter = self._CHEETAH__currentFilter
        
        ########################################
        ## START - generated method body
        
        write(u'''        <!-- PLACEHOLER BODYCONTENT -->
''')
        
        ########################################
        ## END - generated method body
        
        return _dummyTrans and trans.response().getvalue() or ""
        

    def footerContent(self, **KWS):



        ## CHEETAH: generated from #block footerContent at line 37, col 9.
        trans = KWS.get("trans")
        if (not trans and not self._CHEETAH__isBuffering and not callable(self.transaction)):
            trans = self.transaction # is None unless self.awake() was called
        if not trans:
            trans = DummyTransaction()
            _dummyTrans = True
        else: _dummyTrans = False
        write = trans.response().write
        SL = self._CHEETAH__searchList
        _filter = self._CHEETAH__currentFilter
        
        ########################################
        ## START - generated method body
        
        write(u'''        <!-- PLACEHOLER FOOTERCONTENT -->
''')
        
        ########################################
        ## END - generated method body
        
        return _dummyTrans and trans.response().getvalue() or ""
        

    def respond(self, trans=None):



        ## CHEETAH: main method generated for this template
        if (not trans and not self._CHEETAH__isBuffering and not callable(self.transaction)):
            trans = self.transaction # is None unless self.awake() was called
        if not trans:
            trans = DummyTransaction()
            _dummyTrans = True
        else: _dummyTrans = False
        write = trans.response().write
        SL = self._CHEETAH__searchList
        _filter = self._CHEETAH__currentFilter
        
        ########################################
        ## START - generated method body
        
        write(u'''<!DOCTYPE html>


<html lang="en">

<head>

''')
        self._handleCheetahInclude(VFN(VFSL([locals()]+SL+[globals(), builtin],"os.path",True),"join",False)(VFN(VFSL([locals()]+SL+[globals(), builtin],"autosubliminal.PATH",True),"encode",False)(), "web/templates/layout/inc_header.tmpl"), trans=trans, includeFrom="file", raw=False)
        write(u'''
''')
        self.headerContent(trans=trans)
        write(u'''
</head>

<body>

''')
        self._handleCheetahInclude(VFN(VFSL([locals()]+SL+[globals(), builtin],"os.path",True),"join",False)(VFN(VFSL([locals()]+SL+[globals(), builtin],"autosubliminal.PATH",True),"encode",False)(), "web/templates/layout/inc_menu.tmpl"), trans=trans, includeFrom="file", raw=False)
        write(u'''
<div class="jumbotron jumbotron-global">

    <div class="jumbotron-body">

        <div id="stack-context" class="container sticky-notification"></div>

''')
        self.bodyContent(trans=trans)
        write(u'''
    </div>

    <div class="jumbotron-footer">

''')
        self._handleCheetahInclude(VFN(VFSL([locals()]+SL+[globals(), builtin],"os.path",True),"join",False)(VFN(VFSL([locals()]+SL+[globals(), builtin],"autosubliminal.PATH",True),"encode",False)(), "web/templates/layout/inc_footer.tmpl"), trans=trans, includeFrom="file", raw=False)
        write(u'''
''')
        self.footerContent(trans=trans)
        write(u'''
    </div>

</div>

</body>

</html>''')
        
        ########################################
        ## END - generated method body
        
        return _dummyTrans and trans.response().getvalue() or ""
        
    ##################################################
    ## CHEETAH GENERATED ATTRIBUTES


    _CHEETAH__instanceInitialized = False

    _CHEETAH_version = __CHEETAH_version__

    _CHEETAH_versionTuple = __CHEETAH_versionTuple__

    _CHEETAH_genTime = __CHEETAH_genTime__

    _CHEETAH_genTimestamp = __CHEETAH_genTimestamp__

    _CHEETAH_src = __CHEETAH_src__

    _CHEETAH_srcLastModified = __CHEETAH_srcLastModified__

    _mainCheetahMethod_for_PageTemplate= 'respond'

## END CLASS DEFINITION

if not hasattr(PageTemplate, '_initCheetahAttributes'):
    templateAPIClass = getattr(PageTemplate, '_CHEETAH_templateClass', Template)
    templateAPIClass._addCheetahPlumbingCodeToClass(PageTemplate)


# CHEETAH was developed by Tavis Rudd and Mike Orr
# with code, advice and input from many other volunteers.
# For more information visit http://www.CheetahTemplate.org/

##################################################
## if run from command line:
if __name__ == '__main__':
    from Cheetah.TemplateCmdLineIface import CmdLineIface
    CmdLineIface(templateObj=PageTemplate()).run()


