echo off
echo Removing old venv
echo.
cd ../.venv
rmdir pipdeptree /s
cd ..
echo Creating new venv
echo.
python -m venv .venv/pipdeptree
echo Activating venv
echo.
call .venv/pipdeptree/scripts/activate
echo Installing pipdeptree
echo.
python -m pip install pipdeptree
echo Installing libraries
echo.
python -m pip install -r requirements/libraries.txt
echo Generating pipdeptree
echo.
set file=requirements/libraries-pipdeptree.md
echo Libraries dependency tree > %file%
echo ------------------------- >> %file%
echo. >> %file%
echo ### Generated by _.build/generate-pipdeptree.bat_ >> %file%
echo. >> %file%
echo ``` >> %file%
python -m pipdeptree -e pipdeptree -e pywin32 -e setuptools -e Auto-Subliminal >> %file%
echo ``` >> %file%
cd .build