#!/bin/bash

echo 'Generating python dependency files:'

echo '-> Generating requirements.txt ...'
tmpfile=./generated/requirements.txt
file=./generated/requirements.md
poetry export --without-hashes --format requirements.txt --output ./.build/$tmpfile
echo '# Imported dependencies' > $file
echo '' >> $file
echo '### Generated by _../generate-requirements.sh_' >> $file
echo '' >> $file
echo '```' >> $file
cat $tmpfile >> $file
echo '```' >> $file
mv $tmpfile ../requirements.txt

echo '-> Generating requirements-deptree.md ...'
file=./generated/requirements-deptree.md
echo '# Requirements dependency tree' > $file
echo '' >> $file
echo '### Generated by _../generate-requirements.sh_' >> $file
echo '' >> $file
echo '```' >> $file
poetry show --tree --no-dev >> $file
echo '```' >> $file

echo '-> Generating requirements-imported.md ...'
tmpfile=./generated/requirements-pigar.txt
file=./generated/requirements-imported.md
poetry run pigar -p $tmpfile -P ../autosubliminal > /dev/null
echo '# Imported dependencies' > $file
echo '' >> $file
echo '### Generated by _../generate-requirements.sh_' >> $file
echo '' >> $file
echo '```' >> $file
cat $tmpfile >> $file
echo '```' >> $file
rm -f $tmpfile
