echo off
echo Removing old venv
echo.
cd ../.venv
rmdir pipdeptree /s
cd ..
echo.
echo Creating new venv
python -m venv .venv/pipdeptree
echo.
echo Activating venv
call .venv/pipdeptree/scripts/activate
echo.
echo Upgrading pip and setuptools
python -m pip install --upgrade pip
python -m pip install --upgrade setuptools
echo.
echo Installing pipdeptree
echo.
python -m pip install pipdeptree
echo.
echo Installing libraries
echo.
python -m pip install -r requirements/libraries.txt
echo.
echo Generating pipdeptree
echo.
set file=requirements/libraries-pipdeptree.md
echo # Libraries dependency tree>%file%
echo.>>%file%
echo ### Generated by _.build/generate-pipdeptree.bat_>>%file%
echo.>>%file%
echo ```>>%file%
python -m pipdeptree -e pipdeptree -e pywin32 -e setuptools -e Auto-Subliminal >> %file%
echo ```>>%file%
echo.
echo Deactivating venv
call .venv/pipdeptree/scripts/deactivate
cd .build
