# Workflow for continuous integration

name: Continuous integration

on:
  push:
    branches:
      - development
      - master
  pull_request:
    branches:
      - development
      - master

jobs:
  ci:

    runs-on: ${{ matrix.os }} # Use matrix os to run on multiple os
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
        python-version: ['3.7', '3.8', '3.9', '3.10']

    defaults:
      run:
        shell: bash # required for poetry

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Set up python
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}

    - name: Print python version
      run: |
        python --version

    - name: Setup poetry
      uses: snok/install-poetry@v1

    - name: Print poetry version
      run: |
        poetry --version

    - name: Install python dependencies
      run: |
        poetry install --no-interaction

    - name: Get node version (Linux)
      id: get-node-version-linux
      if: ${{ runner.os == 'Linux' }}
      working-directory: web/autosubliminal
      run: |
        echo "::set-output name=node-version::$(jq -r '.engines.node' package.json | sed 's/[>=]//g')"

    - name: Set up node (Linux)
      if: ${{ runner.os == 'Linux' }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ steps.get-node-version-linux.outputs.node-version }}

    - name: Get node version (Windows)
      id: get-node-version-windows
      if: ${{ runner.os == 'Windows' }}
      shell: pwsh # default shell for windows (needed to get node version with powershell)
      working-directory: web/autosubliminal
      run: |
        echo "::set-output name=node-version::$((Get-Content -Raw -Path package.json | ConvertFrom-Json).engines.node -replace '[>=]')"

    - name: Set up node (Windows)
      if: ${{ runner.os == 'Windows' }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ steps.get-node-version-windows.outputs.node-version }}

    - name: Print node version
      run: |
        echo "Node version $(node --version)"
        echo "Npm version $(npm --version)"

    - name: Install npm dependencies
      working-directory: web/autosubliminal
      run: |
        npm install

    - name: Lint python code
      run: |
        # Configuration is done in .flake8
        poetry run flake8 --verbose

    - name: Lint angular code
      working-directory: web/autosubliminal
      run: |
        npm run lint

    - name: Test python code
      run: |
        # Configuration is done in .coveragerc
        poetry run coverage run --module pytest
        poetry run coverage report

    - name: Publish python coverage report
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        COVERALLS_PARALLEL: true
        # Set service name as work around -> https://github.com/TheKevJames/coveralls-python/issues/252
        COVERALLS_SERVICE_NAME: github
      run: |
        poetry run coveralls

  ci-finish:

    needs: ci

    runs-on: ubuntu-latest

    steps:

    - name: Install python dependencies
      run: |
        pip install --upgrade coveralls

    - name: Aggregate python coverage reports
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        coveralls --finish
