# Workflow for a javascript dependency change via pull request

name: Javascript dependency

on:
  pull_request:
    branches:
      - development
    paths:
      - 'web/autosubliminal/package.json'

jobs:
  dependency-js-build:

    defaults:
      run:
        shell: bash
        working-directory: web/autosubliminal

    runs-on: windows-latest

    # Map a step output to a job output
    outputs:
      build-cache-key: ${{ steps.build-cache-key.outputs.cache-key }}

    steps:

    - name: Checkout
      uses: actions/checkout@v2
      with:
        ref: ${{ github.head_ref }} # required for PR (see https://github.com/stefanzweifel/git-auto-commit-action)

    - name: Get node version
      id: get-node-version
      run: |
        echo "::set-output name=node-version::$(jq -r '.engines.node' package.json | sed 's/[>=]//g')"

    - name: Set up node
      uses: actions/setup-node@v2
      with:
        node-version: "${{ steps.get-node-version.outputs.node-version }}"

    - name: Print node version
      run: |
        echo "Node version $(node --version)"
        echo "Npm version $(npm --version)"

    - name: Install js dependency
      run: |
        npm install

    - name: Build application
      run: |
        npm run build

    - name: Build cache key
      id: build-cache-key
      run: |
        echo "::set-output name=cache-key::$(echo '${{ github.repository }}-dependency-js-build-cache-${{ github.run_id }}' | sed 's/\//\-/g;s/\\/\-/g')"

    - name: Cache build
      uses: actions/cache@v2
      with:
        path: .
        key: ${{ steps.build-cache-key.outputs.cache-key }}

  dependency-js-commit:

    needs: dependency-js-build

    defaults:
      run:
        shell: bash
        working-directory: web/autosubliminal

    runs-on: ubuntu-latest

    steps:

    - name: Checkout
      uses: actions/checkout@v2
      with:
        ref: ${{ github.head_ref }} # required for PR (see https://github.com/stefanzweifel/git-auto-commit-action)

    - name: Restore cache build
      uses: actions/cache@v2
      with:
        path: .
        key: ${{ needs.jobs.dependency-js-build.outputs.cache-key }}

    - name: Auto commit changes
      uses: stefanzweifel/git-auto-commit-action@v4
      with:
        commit_message: Install dependency and build application
        commit_user_name: h3llrais3r
        commit_user_email: pooh_beer_1@hotmail.com
        commit_author: h3llrais3r <pooh_beer_1@hotmail.com>
