# Workflow for a javascript dependency change via pull request

name: Javascript dependency

on:
  pull_request:
    branches:
      - development
    paths:
      - web/autosubliminal/package.json
      - web/autosubliminal/package-lock.json
      #- web/autosubliminal/src/** # trigger build for all src changes

jobs:
  dependency-js:

    defaults:
      run:
        shell: bash
        working-directory: web/autosubliminal

    runs-on: windows-latest

    steps:

    - name: Checkout
      uses: actions/checkout@v2
      with:
        ref: ${{ github.head_ref }} # required for on:pull_request

    - name: Get node version
      id: get-node-version
      run: |
        echo "::set-output name=node-version::$(jq -r '.engines.node' package.json | sed 's/[>=]//g')"

    - name: Set up node
      uses: actions/setup-node@v2
      with:
        node-version: ${{ steps.get-node-version.outputs.node-version }}

    - name: Print node version
      run: |
        echo "Node version $(node --version)"
        echo "Npm version $(npm --version)"

    - name: Install js dependency
      run: |
        npm install

    - name: Build application
      run: |
        npm run build

    - name: Check changes
      id: check-changes
      run: |
        echo "Changed files:"
        git status --porcelain
        echo "Checking for real changes (ignoring line endings)"
        changes=$(if $(git diff --quiet); then echo "false"; else echo "true"; fi)
        echo "Changes detected: $changes"
        echo "::set-output name=changes::$changes"

    - name: Commit changes
      if: ${{ steps.check-changes.outputs.changes == 'true' }}
      run: |
        git config --global user.name "github-actions[bot]"
        git config --global user.email "github-actions[bot]@users.noreply.github.com"
        git add --all
        git commit --message "Install dependency and build application" --author "h3llrais3r <pooh_beer_1@hotmail.com>"
        git push

    - name: Add labels
      if: ${{ steps.check-changes.outputs.changes == 'true' }}
      uses: andymckay/labeler@master
      with:
        add-labels: "source changes"

    - name: Remove labels
      if: ${{ steps.check-changes.outputs.changes == 'false' }}
      uses: andymckay/labeler@master
      with:
        remove-labels: "source changes"
